Added Theme Table container and base for Tailwind Custom Themes
Power-Components/livewire-powergrid pull request #1583
Opened 2024-06-04 10:58 UTC by marcheffels

## ⚡ PowerGrid - Pull Request

Welcome and thank you for your interest in contributing to our project!. You must use this template to submit a Pull Request or it will not be accepted.

--- 
#### Motivation

- [ ] Bug fix
- [ ] Enhancement
- [x] New feature
- [ ] Breaking change

#### Description

This Pull Request adds Tailwind Custom Theme container and base.

#### Related Issue(s):  #_____.

#### Documentation

 This PR requires [Documentation](https://github.com/Power-Components/powergrid-doc) update?

- [ ] Yes
- [x] No
- [ ] I have already submitted a Documentation pull request.

2024-06-05 23:33 UTC, luanfreitasdev commented
Thank you @marcheffels

2024-06-05 23:35 UTC, luanfreitasdev commented
I'm afraid this is a breaking change. If the theme was previously published and the class was not extended, there will be a break.

2024-06-11 07:05 UTC, marcheffels commented
Hi @luanfreitasdev, I'm understanding why you cannot marge this PR.

The problem I'm trying to solve is that the current theme is breaking my site.
The negative margin on the container causes the container size to be larger than the parent div.

My current workaround for my site is that I wrap all the tables in a separate div with `overflow-hidden`.

### Suggested solutions:
**1. Remove negative margin:**
Container changes:
From `class="-my-2 overflow-x-auto sm:-mx-3 lg:-mx-8"`
To `class="overflow-x-auto"`
Base changes:
From `class="p-3 align-middle inline-block min-w-full w-full sm:px-6 lg:px-8"`
To `class="align-middle inline-block min-w-full w-full"`
(I tried to find a reason for the negative margin. If there is a reason, please explain it to me.)

**2. Add "overflow-hidden" to the wrapper:**
Change parent of container:
From `class="flex flex-col"`
To `class="flex flex-col overflow-hidden"`

Are any of the suggested solutions acceptable?
Then I can create a new PR.

Thanks.

2024-06-11 19:05 UTC, luanfreitasdev requested changes
Can you check for a bootstrap theme too?

2024-06-11 19:05 UTC, luanfreitasdev commented on resources/views/components/frameworks/tailwind/table-base.blade.php
> +        class="{{ data_get($theme, 'table.containerClass') }}"
Add default values to all data_get methods

```php
class="{{ data_get($theme, 'table.containerClass', '-my-2 overflow-x-auto sm:-mx-3 lg:-mx-8') }}"
```

2024-06-12 07:07 UTC, marcheffels commented on resources/views/components/frameworks/tailwind/table-base.blade.php
> +        class="{{ data_get($theme, 'table.containerClass') }}"
The `data_get` function returns the default value only if the specified key is not found. The `containerClass` and all others are defined as public properties with an initially empty string. Therefore, `data_get` never returns the default value here.

2024-06-12 09:32 UTC, luanfreitasdev commented on resources/views/components/frameworks/tailwind/table-base.blade.php
> +        class="{{ data_get($theme, 'table.containerClass') }}"
This is necessary to maintain compatibility with other themes that do not use the new methods. For example: 

https://github.com/Power-Components/powergrid-demo/blob/powergrid_v5/app/Helpers/PowerGridThemes/TailwindStriped.php

2024-06-12 11:23 UTC, marcheffels commented
> Can you check for a bootstrap theme too?

in Bootstrap theme I can't find any container, base div tag or negative margin, so I believe this problem exists only in Tailwind theme.

2024-06-13 13:49 UTC, luanfreitasdev approved these changes

2024-06-13 13:49 UTC, merged