[4x] Add Multi Sorting
Power-Components/livewire-powergrid pull request #550
Opened 2022-08-08 13:40 UTC by racerguy

Adds Multiple Column Sorting

set public $multiSort to true

Unable to test a clean pull. Please run a test if you don't mind

2022-08-08 20:24 UTC, luanfreitasdev commented
Hi, thanks for submitting your PR to powergrid!.

I will be analyzing some points because there is still much to discuss.

Do you have an example showing how it works or could you submit a test?

2022-08-08 20:30 UTC, luanfreitasdev requested changes
There are some things in your PR that are lagging behind main and have been removed in your PR.

L:152,187,301

2022-08-08 21:44 UTC, racerguy commented
Below is a video had to apply a fix for collections to work.

In the video I have an output at the top of the table which is not in PR below is the code for it.  

`@php
    print_r($sortArray)
@endphp`




https://user-images.githubusercontent.com/64607188/183519769-108c2668-90da-4863-8c7b-baacd305e162.mp4

2022-08-12 08:08 UTC, racerguy commented
> There are some things in your PR that are lagging behind main and have been removed in your PR.
> 
> L:152,187,301

I believe this has been fixed in my latest commit

2022-08-12 20:29 UTC, luanfreitasdev requested changes
The tests will definitely be missing at this point, but we can check the code style and phpstan for now

2022-08-12 20:29 UTC, luanfreitasdev commented on src/PowerGridComponent.php
> +            $sortField = Support\Str::of($this->sortField)->contains('.') || $this->ignoreTablePrefix ? $this->sortField : $this->currentTable . '.' . $this->sortField;
This line is duplicated with the 224

2022-08-12 20:29 UTC, luanfreitasdev commented on src/PowerGridComponent.php
> +            }
Would that work?
```php
$results->orderByRaw(SqlSupport::sortStringAsNumber($sortField) . ' ' . $multiSortDirection ?:  $this->sortDirection);
```

2022-08-12 20:29 UTC, luanfreitasdev commented on src/Traits/WithSorting.php
> +        }
```php
if ($this->multiSort) {
      $this->sortByArray($field);
     
      return;
}

$this->sortDirection = $this->sortField === $field ? $this->reverseSort() : $direction;

$this->sortField = $field;

2022-08-12 20:29 UTC, luanfreitasdev commented on src/Traits/WithSorting.php
> +    /* change */
remove comment

2022-08-12 20:29 UTC, luanfreitasdev commented on src/Traits/WithSorting.php
> +        return $query;
```php
if (is_a($query, Collection::class)) {
     $formattedSortingArray = [];
     foreach ($this->sortArray as $sortField => $sortDirection) {
             array_push($formattedSortingArray, [$sortField , $sortDirection]);
     }
      return  $query->sortBy($formattedSortingArray);
}

foreach ($this->sortArray as $sortField => $sortDirection) {
      $query = $query->orderBy($sortField, $sortDirection);
}

return $query;
```

2022-08-12 21:32 UTC, racerguy commented on src/PowerGridComponent.php
> +            }
Changing in next PR

2022-08-12 21:34 UTC, racerguy commented on src/Traits/WithSorting.php
> +        }
Changing in next PR

2022-08-12 23:38 UTC, luanfreitasdev commented
Test failing is another issue with doctrine/dbal version 3.4. not related

2022-09-26 18:40 UTC, racerguy commented
@luanfreitasdev is there any more work that needs to be completed for this to go into production?

2022-09-27 11:27 UTC, luanfreitasdev commented
I marked it for the next version 4, because of the complexity.
I'm thinking of testing it out before merging.
Documentation is also missing.

2022-09-27 17:41 UTC, racerguy commented
> I marked it for the next version 4, because of the complexity. I'm thinking of testing it out before merging. Documentation is also missing.

Sounds great! will try to get some basic documentation for you

2022-10-09 13:05 UTC, luanfreitasdev approved these changes

2022-10-09 13:12 UTC, merged