Added a Case-insensitive search to the table's Header search input that works on json database column.
Power-Components/livewire-powergrid pull request #877
Opened 2023-03-08 20:35 UTC by chamoux

# ⚡ PowerGrid ⚡ Pull Request

Welcome and thank you for your interest in contributing to our project!. You must use this template to submit a Pull Request or it will not be accepted.

💡 Please complete this template to submit a Pull Request, we cannot accept incomplete Pull Requests.

## Guidelines

`   🗒️ `  Please read the [Contributing Guide](https://github.com/Power-Components/livewire-powergrid/blob/main/CONTRIBUTING.md) and follow all steps listed there.

`   ✍️ `  Give this PR a meaningful title.

`   📣 `  Describe your PR details below.

## Pull Request Information

### Motivation

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change

### Related Issue(s)

This PR Fixes the Issue #_____.

### Description

This Pull Request adds a case-insensitive searching based on the column type where it checks if the column type is JSON it performs a case insensitive query or else performs the old query. Previously JSON columns were case-sensitive.

### Contribution Guide

- [x] I have read and followed the steps listed in the [Contributing Guide](https://github.com/Power-Components/livewire-powergrid/blob/main/CONTRIBUTING.md).

### Documentation

 This PR requires [Documentation](https://github.com/Power-Components/powergrid-doc) update?

- [ ] Yes
- [x] No
- [ ] I have already submitted a Documentation pull request.

2023-03-08 22:38 UTC, luanfreitasdev commented
Hello!. Thanks for this contributing.
Can you send any test ?

2023-03-09 11:44 UTC, chamoux commented
Test Results:
![tests](https://user-images.githubusercontent.com/29353763/224012261-5febe1cc-125e-47c1-a6a0-86470dad908c.jpg)

Testing Table in a laravel project:
https://user-images.githubusercontent.com/29353763/224012840-4af33038-afc9-4161-a9d0-d1363a2799f0.mp4

DB Structure:
![DB-Structure](https://user-images.githubusercontent.com/29353763/224013322-e74f1cea-bb8a-453b-adb4-ff67bcc7406e.jpg)

2023-03-09 13:39 UTC, luanfreitasdev commented
Hello!. I did a test to ensure that in all databases this change has no influence, but in PostgreeSQL it seems that it is not possible to use LOWER as in mysql. Can you verify this issue so we can move on with the PR?

![image](https://user-images.githubusercontent.com/33601626/224039572-62d4ecc2-f2a8-4101-a320-3d1ca307ebf1.png)

2023-03-09 14:11 UTC, luanfreitasdev requested changes

2023-03-09 14:11 UTC, luanfreitasdev commented on src/Helpers/Model.php
> +                                $query->orWhereRaw('LOWER(`' . $table . '` .`' . $field . '`)' . SqlSupport::like($query) . '?', '%' . strtolower($this->powerGridComponent->search) . '%');
```php
$query->orWhereRaw('LOWER(`' . $table . '` .`' . $field . '`) ' . SqlSupport::like($query) . '?', '%' . strtolower($this->powerGridComponent->search) . '%');
```

I think if adding space before SqlSupport might work

https://w3resource.com/PostgreSQL/lower-function.php

2023-03-09 14:27 UTC, luanfreitasdev commented on src/Helpers/Model.php
> +                                $query->orWhereRaw('LOWER(`' . $table . '` .`' . $field . '`)' . SqlSupport::like($query) . '?', '%' . strtolower($this->powerGridComponent->search) . '%');
I think Postgree doesn't recognize the dot(.) this: LOWER(table.field)

2023-03-09 14:28 UTC, chamoux commented
It seems in SQL you can use Lower on the entire JSON column but in pgsql you need to use it on a property like so ```lower(column->>property)``` I will commit the spaces and remove the if check since it passed the tests on my end you might want to check after me once more.
Thank you

2023-03-09 16:27 UTC, merged

2023-03-09 16:45 UTC, chamoux commented
Second Round of tests:
![Tests2](https://user-images.githubusercontent.com/29353763/224092632-e5162fd6-9d9f-4bca-bea2-f9b71ffb762c.jpg)
Since ILIKE Already accomplishes what is needed as shown below:
![pgsql](https://user-images.githubusercontent.com/29353763/224092756-4fb9a0b3-78a6-40b3-85f5-cf3b873b9534.jpg)
we can check the database type if it is different that pgsql then we execute the new query else execute the old one.